export { default as HAvatar } from './avatar.js';
export { default as HAvatarGroup } from './avatar-group.js';
export { default as HBar } from './bar.js';
export { default as HBreadcrumbs } from './breadcrumbs.js';
export { default as HBreadcrumbsItem } from './breadcrumbs-item.js';
export { default as HBusyIndicator } from './busy-indicator.js';
export { default as HButton } from './button.js';
export { default as HButtonBadge } from './button-badge.js';
export { default as HCalendar } from './calendar.js';
export { default as HCalendarDate } from './calendar-date.js';
export { default as HCalendarDateRange } from './calendar-date-range.js';
export { default as HSpecialCalendarDate } from './special-calendar-date.js';
export { default as HCalendarLegend } from './calendar-legend.js';
export { default as HCalendarLegendItem } from './calendar-legend-item.js';
export { default as HCard } from './card.js';
export { default as HCardHeader } from './card-header.js';
export { default as HCarousel } from './carousel.js';
export { default as HCheckBox } from './checkbox.js';
export { default as HColorPalette } from './color-palette.js';
export { default as HColorPaletteItem } from './color-palette-item.js';
export { default as HColorPalettePopover } from './color-palette-popover.js';
export { default as HColorPicker } from './color-picker.js';
export { default as HComboBox } from './combobox.js';
export { default as HComboBoxItem } from './combobox-item.js';
export { default as HComboBoxItemGroup } from './combobox-item-group.js';
export { default as HDatePicker } from './date-picker.js';
export { default as HDateRangePicker } from './date-range-picker.js';
export { default as HDateTimePicker } from './date-time-picker.js';
export { default as HDialog } from './dialog.js';
export { default as HExpandableText } from './expandable-text.js';
export { default as HFileUploader } from './file-uploader.js';
export { default as HForm } from './form.js';
export { default as HFormGroup } from './form-group.js';
export { default as HFormItem } from './form-item.js';
export { default as HIcon } from './icon.js';
export { default as HInput } from './input.js';
export { default as HSuggestionItem } from './suggestion-item.js';
export { default as HSuggestionItemCustom } from './suggestion-item-custom.js';
export { default as HSuggestionItemGroup } from './suggestion-item-group.js';
export { default as HLabel } from './label.js';
export { default as HLink } from './link.js';
export { default as HList } from './list.js';
export { default as HListItemCustom } from './list-item-custom.js';
export { default as HListItemGroup } from './list-item-group.js';
export { default as HListItemStandard } from './list-item-standard.js';
export { default as HMenu } from './menu.js';
export { default as HMenuItem } from './menu-item.js';
export { default as HMenuSeparator } from './menu-separator.js';
export { default as HMessageStrip } from './message-strip.js';
export { default as HMultiComboBox } from './multi-combobox.js';
export { default as HMultiComboBoxItem } from './multi-combobox-item.js';
export { default as HMultiComboBoxItemGroup } from './multi-combobox-item-group.js';
export { default as HMultiInput } from './multi-input.js';
export { default as HPanel } from './panel.js';
export { default as HPopover } from './popover.js';
export { default as HProgressIndicator } from './progress-indicator.js';
export { default as HRadioButton } from './radio-button.js';
export { default as HRangeSlider } from './range-slider.js';
export { default as HRatingIndicator } from './rating-indicator.js';
export { default as HResponsivePopover } from './responsive-popover.js';
export { default as HSegmentedButton } from './segmented-button.js';
export { default as HSegmentedButtonItem } from './segmented-button-item.js';
export { default as HSelect } from './select.js';
export { default as HOption } from './option.js';
export { default as HOptionCustom } from './option-custom.js';
export { default as HSlider } from './slider.js';
export { default as HSplitButton } from './split-button.js';
export { default as HStepInput } from './step-input.js';
export { default as HSwitch } from './switch.js';
export { default as HTabContainer } from './tab-container.js';
export { default as HTab } from './tab.js';
export { default as HTabSeparator } from './tab-separator.js';
export { default as HTable } from './table.js';
export { default as HTableCell } from './table-cell.js';
export { default as HTableGrowing } from './table-growing.js';
export { default as HTableHeaderCell } from './table-header-cell.js';
export { default as HTableHeaderRow } from './table-header-row.js';
export { default as HTableRow } from './table-row.js';
export { default as HTableRowAction } from './table-row-action.js';
export { default as HTableRowActionNavigation } from './table-row-action-navigation.js';
export { default as HTableSelection } from './table-selection.js';
export { default as HTableVirtualizer } from './table-virtualizer.js';
export { default as HTag } from './tag.js';
export { default as HText } from './text.js';
export { default as HTextArea } from './textarea.js';
export { default as HTimePicker } from './time-picker.js';
export { default as HTitle } from './title.js';
export { default as HToast } from './toast.js';
export { default as HToggleButton } from './toggle-button.js';
export { default as HToken } from './token.js';
export { default as HTokenizer } from './tokenizer.js';
export { default as HToolbar } from './toolbar.js';
export { default as HToolbarButton } from './toolbar-button.js';
export { default as HToolbarSelect } from './toolbar-select.js';
export { default as HToolbarSelectOption } from './toolbar-select-option.js';
export { default as HToolbarSeparator } from './toolbar-separator.js';
export { default as HToolbarSpacer } from './toolbar-spacer.js';
export { default as HTree } from './tree.js';
export { default as HTreeItem } from './tree-item.js';
export { default as HTreeItemCustom } from './tree-item-custom.js';
export { default as HNavigationLayout, NavigationLayoutMode } from './navigation-layout.js';
export { default as HNotificationList } from './notification-list.js';
export { default as HNotificationListGroupItem } from './notification-list-group-item.js';
export { default as HNotificationListItem } from './notification-list-item.js';
export { default as HProductSwitch } from './product-switch.js';
export { default as HProductSwitchItem } from './product-switch-item.js';
export { default as HShellBar } from './shellbar.js';
export { default as HShellBarItem } from './shellbar-item.js';
export { default as HShellBarSpacer } from './shellbar-spacer.js';
export { default as HSideNavigation } from './side-navigation.js';
export { default as HSideNavigationGroup } from './side-navigation-group.js';
export { default as HSideNavigationItem } from './side-navigation-item.js';
export { default as HSideNavigationSubItem } from './side-navigation-sub-item.js';
export { default as HUploadCollection } from './upload-collection.js';
export { default as HUploadCollectionItem } from './upload-collection-item.js';
export { default as HWizard } from './wizard.js';
export { default as HWizardStep } from './wizard-step.js';
// Icons
import '@ui5/webcomponents-icons/dist/Chart-Tree-Map.js';
import '@ui5/webcomponents-icons/dist/Netweaver-business-client.js';
import '@ui5/webcomponents-icons/dist/accelerated.js';
import '@ui5/webcomponents-icons/dist/accept.js';
import '@ui5/webcomponents-icons/dist/accessibility.js';
import '@ui5/webcomponents-icons/dist/accidental-leave.js';
import '@ui5/webcomponents-icons/dist/account.js';
import '@ui5/webcomponents-icons/dist/accounting-document-verification.js';
import '@ui5/webcomponents-icons/dist/action-settings.js';
import '@ui5/webcomponents-icons/dist/action.js';
import '@ui5/webcomponents-icons/dist/activate.js';
import '@ui5/webcomponents-icons/dist/activities.js';
import '@ui5/webcomponents-icons/dist/activity-2.js';
import '@ui5/webcomponents-icons/dist/activity-assigned-to-goal.js';
import '@ui5/webcomponents-icons/dist/activity-individual.js';
import '@ui5/webcomponents-icons/dist/activity-items.js';
import '@ui5/webcomponents-icons/dist/add-activity-2.js';
import '@ui5/webcomponents-icons/dist/add-activity.js';
import '@ui5/webcomponents-icons/dist/add-calendar.js';
import '@ui5/webcomponents-icons/dist/add-contact.js';
import '@ui5/webcomponents-icons/dist/add-coursebook.js';
import '@ui5/webcomponents-icons/dist/add-document.js';
import '@ui5/webcomponents-icons/dist/add-employee.js';
import '@ui5/webcomponents-icons/dist/add-equipment.js';
import '@ui5/webcomponents-icons/dist/add-favorite.js';
import '@ui5/webcomponents-icons/dist/add-filter.js';
import '@ui5/webcomponents-icons/dist/add-folder.js';
import '@ui5/webcomponents-icons/dist/add-photo.js';
import '@ui5/webcomponents-icons/dist/add-process.js';
import '@ui5/webcomponents-icons/dist/add-product.js';
import '@ui5/webcomponents-icons/dist/add.js';
import '@ui5/webcomponents-icons/dist/address-book.js';
import '@ui5/webcomponents-icons/dist/addresses.js';
import '@ui5/webcomponents-icons/dist/ai.js';
import '@ui5/webcomponents-icons/dist/alert.js';
import '@ui5/webcomponents-icons/dist/along-stacked-chart.js';
import '@ui5/webcomponents-icons/dist/alphabetical-order.js';
import '@ui5/webcomponents-icons/dist/appear-offline.js';
import '@ui5/webcomponents-icons/dist/appointment-2.js';
import '@ui5/webcomponents-icons/dist/appointment.js';
import '@ui5/webcomponents-icons/dist/approvals.js';
import '@ui5/webcomponents-icons/dist/area-chart.js';
import '@ui5/webcomponents-icons/dist/arobase.js';
import '@ui5/webcomponents-icons/dist/arrow-bottom.js';
import '@ui5/webcomponents-icons/dist/arrow-down.js';
import '@ui5/webcomponents-icons/dist/arrow-left.js';
import '@ui5/webcomponents-icons/dist/arrow-right.js';
import '@ui5/webcomponents-icons/dist/arrow-top.js';
import '@ui5/webcomponents-icons/dist/attachment-audio.js';
import '@ui5/webcomponents-icons/dist/attachment-e-pub.js';
import '@ui5/webcomponents-icons/dist/attachment-html.js';
import '@ui5/webcomponents-icons/dist/attachment-photo.js';
import '@ui5/webcomponents-icons/dist/attachment-text-file.js';
import '@ui5/webcomponents-icons/dist/attachment-video.js';
import '@ui5/webcomponents-icons/dist/attachment-zip-file.js';
import '@ui5/webcomponents-icons/dist/attachment.js';
import '@ui5/webcomponents-icons/dist/away.js';
import '@ui5/webcomponents-icons/dist/back-to-top.js';
import '@ui5/webcomponents-icons/dist/background.js';
import '@ui5/webcomponents-icons/dist/badge.js';
import '@ui5/webcomponents-icons/dist/bar-chart.js';
import '@ui5/webcomponents-icons/dist/bar-code.js';
import '@ui5/webcomponents-icons/dist/basket.js';
import '@ui5/webcomponents-icons/dist/batch-payments.js';
import '@ui5/webcomponents-icons/dist/bbyd-active-sales.js';
import '@ui5/webcomponents-icons/dist/bbyd-dashboard.js';
import '@ui5/webcomponents-icons/dist/bed.js';
import '@ui5/webcomponents-icons/dist/begin.js';
import '@ui5/webcomponents-icons/dist/bell-2.js';
import '@ui5/webcomponents-icons/dist/bell.js';
import '@ui5/webcomponents-icons/dist/biometric-face.js';
import '@ui5/webcomponents-icons/dist/biometric-thumb.js';
import '@ui5/webcomponents-icons/dist/blank-tag-2.js';
import '@ui5/webcomponents-icons/dist/blank-tag.js';
import '@ui5/webcomponents-icons/dist/blur.js';
import '@ui5/webcomponents-icons/dist/bo-strategy-management.js';
import '@ui5/webcomponents-icons/dist/bold-text.js';
import '@ui5/webcomponents-icons/dist/bookmark-2.js';
import '@ui5/webcomponents-icons/dist/bookmark.js';
import '@ui5/webcomponents-icons/dist/border.js';
import '@ui5/webcomponents-icons/dist/broken-link.js';
import '@ui5/webcomponents-icons/dist/browse-folder.js';
import '@ui5/webcomponents-icons/dist/bubble-chart.js';
import '@ui5/webcomponents-icons/dist/building.js';
import '@ui5/webcomponents-icons/dist/bullet-text.js';
import '@ui5/webcomponents-icons/dist/burglary.js';
import '@ui5/webcomponents-icons/dist/bus-public-transport.js';
import '@ui5/webcomponents-icons/dist/business-by-design.js';
import '@ui5/webcomponents-icons/dist/business-card.js';
import '@ui5/webcomponents-icons/dist/business-objects-experience.js';
import '@ui5/webcomponents-icons/dist/business-objects-explorer.js';
import '@ui5/webcomponents-icons/dist/business-objects-mobile.js';
import '@ui5/webcomponents-icons/dist/business-one.js';
import '@ui5/webcomponents-icons/dist/busy.js';
import '@ui5/webcomponents-icons/dist/calendar.js';
import '@ui5/webcomponents-icons/dist/call.js';
import '@ui5/webcomponents-icons/dist/camera.js';
import '@ui5/webcomponents-icons/dist/cancel-maintenance.js';
import '@ui5/webcomponents-icons/dist/cancel-share.js';
import '@ui5/webcomponents-icons/dist/cancel.js';
import '@ui5/webcomponents-icons/dist/capital-projects.js';
import '@ui5/webcomponents-icons/dist/car-rental.js';
import '@ui5/webcomponents-icons/dist/card.js';
import '@ui5/webcomponents-icons/dist/cargo-train.js';
import '@ui5/webcomponents-icons/dist/cart-2.js';
import '@ui5/webcomponents-icons/dist/cart-3.js';
import '@ui5/webcomponents-icons/dist/cart-4.js';
import '@ui5/webcomponents-icons/dist/cart-5.js';
import '@ui5/webcomponents-icons/dist/cart-approval.js';
import '@ui5/webcomponents-icons/dist/cart-full.js';
import '@ui5/webcomponents-icons/dist/cart.js';
import '@ui5/webcomponents-icons/dist/cause.js';
import '@ui5/webcomponents-icons/dist/chain-link.js';
import '@ui5/webcomponents-icons/dist/chalkboard.js';
import '@ui5/webcomponents-icons/dist/chart-axis.js';
import '@ui5/webcomponents-icons/dist/chart-table-view.js';
import '@ui5/webcomponents-icons/dist/check-availability.js';
import '@ui5/webcomponents-icons/dist/checklist-2.js';
import '@ui5/webcomponents-icons/dist/checklist-item-2.js';
import '@ui5/webcomponents-icons/dist/checklist-item.js';
import '@ui5/webcomponents-icons/dist/checklist.js';
import '@ui5/webcomponents-icons/dist/chevron-phase-2.js';
import '@ui5/webcomponents-icons/dist/chevron-phase.js';
import '@ui5/webcomponents-icons/dist/choropleth-chart.js';
import '@ui5/webcomponents-icons/dist/circle-task-2.js';
import '@ui5/webcomponents-icons/dist/circle-task.js';
import '@ui5/webcomponents-icons/dist/citizen-connect.js';
import '@ui5/webcomponents-icons/dist/clear-all.js';
import '@ui5/webcomponents-icons/dist/clear-filter.js';
import '@ui5/webcomponents-icons/dist/clinical-order.js';
import '@ui5/webcomponents-icons/dist/clinical-task-tracker.js';
import '@ui5/webcomponents-icons/dist/clinical-tast-tracker.js';
import '@ui5/webcomponents-icons/dist/close-command-field.js';
import '@ui5/webcomponents-icons/dist/cloud-check.js';
import '@ui5/webcomponents-icons/dist/cloud.js';
import '@ui5/webcomponents-icons/dist/co.js';
import '@ui5/webcomponents-icons/dist/collaborate.js';
import '@ui5/webcomponents-icons/dist/collapse-all.js';
import '@ui5/webcomponents-icons/dist/collapse-group.js';
import '@ui5/webcomponents-icons/dist/collapse.js';
import '@ui5/webcomponents-icons/dist/collections-insight.js';
import '@ui5/webcomponents-icons/dist/collections-management.js';
import '@ui5/webcomponents-icons/dist/collision.js';
import '@ui5/webcomponents-icons/dist/color-fill.js';
import '@ui5/webcomponents-icons/dist/column-chart-dual-axis.js';
import '@ui5/webcomponents-icons/dist/combine.js';
import '@ui5/webcomponents-icons/dist/command-line-interfaces.js';
import '@ui5/webcomponents-icons/dist/comment.js';
import '@ui5/webcomponents-icons/dist/commission-check.js';
import '@ui5/webcomponents-icons/dist/company-view.js';
import '@ui5/webcomponents-icons/dist/compare-2.js';
import '@ui5/webcomponents-icons/dist/compare.js';
import '@ui5/webcomponents-icons/dist/competitor.js';
import '@ui5/webcomponents-icons/dist/complete.js';
import '@ui5/webcomponents-icons/dist/connected.js';
import '@ui5/webcomponents-icons/dist/contacts.js';
import '@ui5/webcomponents-icons/dist/copy.js';
import '@ui5/webcomponents-icons/dist/course-book.js';
import '@ui5/webcomponents-icons/dist/course-program.js';
import '@ui5/webcomponents-icons/dist/create-entry-time.js';
import '@ui5/webcomponents-icons/dist/create-form.js';
import '@ui5/webcomponents-icons/dist/create-leave-request.js';
import '@ui5/webcomponents-icons/dist/create-session.js';
import '@ui5/webcomponents-icons/dist/create.js';
import '@ui5/webcomponents-icons/dist/credit-card.js';
import '@ui5/webcomponents-icons/dist/crm-sales.js';
import '@ui5/webcomponents-icons/dist/crm-service-manager.js';
import '@ui5/webcomponents-icons/dist/crop.js';
import '@ui5/webcomponents-icons/dist/crossed-line-chart.js';
import '@ui5/webcomponents-icons/dist/currency.js';
import '@ui5/webcomponents-icons/dist/curriculum.js';
import '@ui5/webcomponents-icons/dist/cursor-arrow.js';
import '@ui5/webcomponents-icons/dist/customer-and-contacts.js';
import '@ui5/webcomponents-icons/dist/customer-and-supplier.js';
import '@ui5/webcomponents-icons/dist/customer-briefing.js';
import '@ui5/webcomponents-icons/dist/customer-financial-fact-sheet.js';
import '@ui5/webcomponents-icons/dist/customer-history.js';
import '@ui5/webcomponents-icons/dist/customer-order-entry.js';
import '@ui5/webcomponents-icons/dist/customer-view.js';
import '@ui5/webcomponents-icons/dist/customer.js';
import '@ui5/webcomponents-icons/dist/customize.js';
import '@ui5/webcomponents-icons/dist/da-2.js';
import '@ui5/webcomponents-icons/dist/da.js';
import '@ui5/webcomponents-icons/dist/dark-mode.js';
import '@ui5/webcomponents-icons/dist/database.js';
import '@ui5/webcomponents-icons/dist/date-time.js';
import '@ui5/webcomponents-icons/dist/decision.js';
import '@ui5/webcomponents-icons/dist/decline.js';
import '@ui5/webcomponents-icons/dist/decrease-line-height.js';
import '@ui5/webcomponents-icons/dist/delete.js';
import '@ui5/webcomponents-icons/dist/desktop-mobile.js';
import '@ui5/webcomponents-icons/dist/detail-less.js';
import '@ui5/webcomponents-icons/dist/detail-more.js';
import '@ui5/webcomponents-icons/dist/detail-view.js';
import '@ui5/webcomponents-icons/dist/developer-settings.js';
import '@ui5/webcomponents-icons/dist/dimension.js';
import '@ui5/webcomponents-icons/dist/direction-arrows.js';
import '@ui5/webcomponents-icons/dist/disconnected.js';
import '@ui5/webcomponents-icons/dist/discussion-2.js';
import '@ui5/webcomponents-icons/dist/discussion.js';
import '@ui5/webcomponents-icons/dist/dishwasher.js';
import '@ui5/webcomponents-icons/dist/display-more.js';
import '@ui5/webcomponents-icons/dist/display.js';
import '@ui5/webcomponents-icons/dist/doc-attachment.js';
import '@ui5/webcomponents-icons/dist/doctor.js';
import '@ui5/webcomponents-icons/dist/document-text.js';
import '@ui5/webcomponents-icons/dist/document.js';
import '@ui5/webcomponents-icons/dist/documents.js';
import '@ui5/webcomponents-icons/dist/donut-chart.js';
import '@ui5/webcomponents-icons/dist/down.js';
import '@ui5/webcomponents-icons/dist/download-from-cloud.js';
import '@ui5/webcomponents-icons/dist/download.js';
import '@ui5/webcomponents-icons/dist/draw-rectangle.js';
import '@ui5/webcomponents-icons/dist/drill-down.js';
import '@ui5/webcomponents-icons/dist/drill-up.js';
import '@ui5/webcomponents-icons/dist/drop-down-list.js';
import '@ui5/webcomponents-icons/dist/dropdown.js';
import '@ui5/webcomponents-icons/dist/duplicate.js';
import '@ui5/webcomponents-icons/dist/e-care.js';
import '@ui5/webcomponents-icons/dist/e-learning.js';
import '@ui5/webcomponents-icons/dist/eam-work-order.js';
import '@ui5/webcomponents-icons/dist/edit-outside.js';
import '@ui5/webcomponents-icons/dist/edit.js';
import '@ui5/webcomponents-icons/dist/education.js';
import '@ui5/webcomponents-icons/dist/electrocardiogram.js';
import '@ui5/webcomponents-icons/dist/electronic-medical-record.js';
import '@ui5/webcomponents-icons/dist/email-read.js';
import '@ui5/webcomponents-icons/dist/email.js';
import '@ui5/webcomponents-icons/dist/employee-approvals.js';
import '@ui5/webcomponents-icons/dist/employee-lookup.js';
import '@ui5/webcomponents-icons/dist/employee-pane.js';
import '@ui5/webcomponents-icons/dist/employee-rejections.js';
import '@ui5/webcomponents-icons/dist/employee.js';
import '@ui5/webcomponents-icons/dist/enablement.js';
import '@ui5/webcomponents-icons/dist/end-user-experience-monitoring.js';
import '@ui5/webcomponents-icons/dist/endoscopy.js';
import '@ui5/webcomponents-icons/dist/energy-saving-lightbulb.js';
import '@ui5/webcomponents-icons/dist/enter-more.js';
import '@ui5/webcomponents-icons/dist/eraser.js';
import '@ui5/webcomponents-icons/dist/error.js';
import '@ui5/webcomponents-icons/dist/example.js';
import '@ui5/webcomponents-icons/dist/excel-attachment.js';
import '@ui5/webcomponents-icons/dist/exit-full-screen.js';
import '@ui5/webcomponents-icons/dist/expand-all.js';
import '@ui5/webcomponents-icons/dist/expand-group.js';
import '@ui5/webcomponents-icons/dist/expand.js';
import '@ui5/webcomponents-icons/dist/expense-report.js';
import '@ui5/webcomponents-icons/dist/explorer.js';
import '@ui5/webcomponents-icons/dist/factory.js';
import '@ui5/webcomponents-icons/dist/fallback.js';
import '@ui5/webcomponents-icons/dist/family-care.js';
import '@ui5/webcomponents-icons/dist/family-protection.js';
import '@ui5/webcomponents-icons/dist/favorite-list.js';
import '@ui5/webcomponents-icons/dist/favorite.js';
import '@ui5/webcomponents-icons/dist/fax-machine.js';
import '@ui5/webcomponents-icons/dist/feed.js';
import '@ui5/webcomponents-icons/dist/feedback.js';
import '@ui5/webcomponents-icons/dist/feeder-arrow.js';
import '@ui5/webcomponents-icons/dist/female.js';
import '@ui5/webcomponents-icons/dist/filter-analytics.js';
import '@ui5/webcomponents-icons/dist/filter-facets.js';
import '@ui5/webcomponents-icons/dist/filter-fields.js';
import '@ui5/webcomponents-icons/dist/filter.js';
import '@ui5/webcomponents-icons/dist/flag-2.js';
import '@ui5/webcomponents-icons/dist/flag.js';
import '@ui5/webcomponents-icons/dist/flight.js';
import '@ui5/webcomponents-icons/dist/fob-watch.js';
import '@ui5/webcomponents-icons/dist/folder-2.js';
import '@ui5/webcomponents-icons/dist/folder-blank.js';
import '@ui5/webcomponents-icons/dist/folder-full.js';
import '@ui5/webcomponents-icons/dist/folder.js';
import '@ui5/webcomponents-icons/dist/form.js';
import '@ui5/webcomponents-icons/dist/forward.js';
import '@ui5/webcomponents-icons/dist/fridge.js';
import '@ui5/webcomponents-icons/dist/full-screen.js';
import '@ui5/webcomponents-icons/dist/full-stacked-chart.js';
import '@ui5/webcomponents-icons/dist/full-stacked-column-chart.js';
import '@ui5/webcomponents-icons/dist/functional-location.js';
import '@ui5/webcomponents-icons/dist/future.js';
import '@ui5/webcomponents-icons/dist/fx.js';
import '@ui5/webcomponents-icons/dist/gantt-bars.js';
import '@ui5/webcomponents-icons/dist/gender-male-and-female.js';
import '@ui5/webcomponents-icons/dist/general-leave-request.js';
import '@ui5/webcomponents-icons/dist/generate-shortcut.js';
import '@ui5/webcomponents-icons/dist/geographic-bubble-chart.js';
import '@ui5/webcomponents-icons/dist/globe.js';
import '@ui5/webcomponents-icons/dist/goal.js';
import '@ui5/webcomponents-icons/dist/goalseek.js';
import '@ui5/webcomponents-icons/dist/grid.js';
import '@ui5/webcomponents-icons/dist/group-2.js';
import '@ui5/webcomponents-icons/dist/group.js';
import '@ui5/webcomponents-icons/dist/header.js';
import '@ui5/webcomponents-icons/dist/heading1.js';
import '@ui5/webcomponents-icons/dist/heading2.js';
import '@ui5/webcomponents-icons/dist/heading3.js';
import '@ui5/webcomponents-icons/dist/headset.js';
import '@ui5/webcomponents-icons/dist/heart-2.js';
import '@ui5/webcomponents-icons/dist/heart.js';
import '@ui5/webcomponents-icons/dist/heating-cooling.js';
import '@ui5/webcomponents-icons/dist/heatmap-chart.js';
import '@ui5/webcomponents-icons/dist/hello-world.js';
import '@ui5/webcomponents-icons/dist/hide.js';
import '@ui5/webcomponents-icons/dist/high-priority.js';
import '@ui5/webcomponents-icons/dist/hint.js';
import '@ui5/webcomponents-icons/dist/history.js';
import '@ui5/webcomponents-icons/dist/home-share.js';
import '@ui5/webcomponents-icons/dist/home.js';
import '@ui5/webcomponents-icons/dist/horizontal-bar-chart-2.js';
import '@ui5/webcomponents-icons/dist/horizontal-bar-chart.js';
import '@ui5/webcomponents-icons/dist/horizontal-bullet-chart.js';
import '@ui5/webcomponents-icons/dist/horizontal-combination-chart.js';
import '@ui5/webcomponents-icons/dist/horizontal-grip.js';
import '@ui5/webcomponents-icons/dist/horizontal-stacked-chart.js';
import '@ui5/webcomponents-icons/dist/horizontal-waterfall-chart.js';
import '@ui5/webcomponents-icons/dist/hr-approval.js';
import '@ui5/webcomponents-icons/dist/idea-wall.js';
import '@ui5/webcomponents-icons/dist/image-viewer.js';
import '@ui5/webcomponents-icons/dist/in-progress-2.js';
import '@ui5/webcomponents-icons/dist/in-progress.js';
import '@ui5/webcomponents-icons/dist/inbox.js';
import '@ui5/webcomponents-icons/dist/incident.js';
import '@ui5/webcomponents-icons/dist/incoming-call.js';
import '@ui5/webcomponents-icons/dist/increase-line-height.js';
import '@ui5/webcomponents-icons/dist/indent.js';
import '@ui5/webcomponents-icons/dist/information.js';
import '@ui5/webcomponents-icons/dist/initiative.js';
import '@ui5/webcomponents-icons/dist/inspect-down.js';
import '@ui5/webcomponents-icons/dist/inspect.js';
import '@ui5/webcomponents-icons/dist/inspection.js';
import '@ui5/webcomponents-icons/dist/instance.js';
import '@ui5/webcomponents-icons/dist/insurance-car.js';
import '@ui5/webcomponents-icons/dist/insurance-house.js';
import '@ui5/webcomponents-icons/dist/insurance-life.js';
import '@ui5/webcomponents-icons/dist/internet-browser.js';
import '@ui5/webcomponents-icons/dist/inventory.js';
import '@ui5/webcomponents-icons/dist/ipad-2.js';
import '@ui5/webcomponents-icons/dist/ipad.js';
import '@ui5/webcomponents-icons/dist/iphone-2.js';
import '@ui5/webcomponents-icons/dist/iphone.js';
import '@ui5/webcomponents-icons/dist/it-host.js';
import '@ui5/webcomponents-icons/dist/it-instance.js';
import '@ui5/webcomponents-icons/dist/it-system.js';
import '@ui5/webcomponents-icons/dist/italic-text.js';
import '@ui5/webcomponents-icons/dist/jam.js';
import '@ui5/webcomponents-icons/dist/journey-arrive.js';
import '@ui5/webcomponents-icons/dist/journey-change.js';
import '@ui5/webcomponents-icons/dist/journey-depart.js';
import '@ui5/webcomponents-icons/dist/key-user-settings.js';
import '@ui5/webcomponents-icons/dist/key.js';
import '@ui5/webcomponents-icons/dist/keyboard-and-mouse.js';
import '@ui5/webcomponents-icons/dist/kpi-corporate-performance.js';
import '@ui5/webcomponents-icons/dist/kpi-managing-my-area.js';
import '@ui5/webcomponents-icons/dist/lab.js';
import '@ui5/webcomponents-icons/dist/laptop.js';
import '@ui5/webcomponents-icons/dist/lateness.js';
import '@ui5/webcomponents-icons/dist/lead-outdated.js';
import '@ui5/webcomponents-icons/dist/lead.js';
import '@ui5/webcomponents-icons/dist/leads.js';
import '@ui5/webcomponents-icons/dist/learning-assistant.js';
import '@ui5/webcomponents-icons/dist/legend.js';
import '@ui5/webcomponents-icons/dist/less.js';
import '@ui5/webcomponents-icons/dist/letter.js';
import '@ui5/webcomponents-icons/dist/light-mode.js';
import '@ui5/webcomponents-icons/dist/lightbulb.js';
import '@ui5/webcomponents-icons/dist/line-chart-dual-axis.js';
import '@ui5/webcomponents-icons/dist/line-chart-time-axis.js';
import '@ui5/webcomponents-icons/dist/line-chart.js';
import '@ui5/webcomponents-icons/dist/line-charts.js';
import '@ui5/webcomponents-icons/dist/list.js';
import '@ui5/webcomponents-icons/dist/loan.js';
import '@ui5/webcomponents-icons/dist/locate-me-2.js';
import '@ui5/webcomponents-icons/dist/locate-me.js';
import '@ui5/webcomponents-icons/dist/locked.js';
import '@ui5/webcomponents-icons/dist/log.js';
import '@ui5/webcomponents-icons/dist/machine.js';
import '@ui5/webcomponents-icons/dist/male.js';
import '@ui5/webcomponents-icons/dist/manager-insight.js';
import '@ui5/webcomponents-icons/dist/manager.js';
import '@ui5/webcomponents-icons/dist/map-2.js';
import '@ui5/webcomponents-icons/dist/map-3.js';
import '@ui5/webcomponents-icons/dist/map-fill.js';
import '@ui5/webcomponents-icons/dist/map.js';
import '@ui5/webcomponents-icons/dist/marketing-campaign.js';
import '@ui5/webcomponents-icons/dist/master-task-triangle-2.js';
import '@ui5/webcomponents-icons/dist/master-task-triangle.js';
import '@ui5/webcomponents-icons/dist/meal.js';
import '@ui5/webcomponents-icons/dist/measure.js';
import '@ui5/webcomponents-icons/dist/measurement-document.js';
import '@ui5/webcomponents-icons/dist/measuring-point.js';
import '@ui5/webcomponents-icons/dist/media-forward.js';
import '@ui5/webcomponents-icons/dist/media-pause.js';
import '@ui5/webcomponents-icons/dist/media-play.js';
import '@ui5/webcomponents-icons/dist/media-reverse.js';
import '@ui5/webcomponents-icons/dist/media-rewind.js';
import '@ui5/webcomponents-icons/dist/meeting-room.js';
import '@ui5/webcomponents-icons/dist/megamenu.js';
import '@ui5/webcomponents-icons/dist/menu.js';
import '@ui5/webcomponents-icons/dist/menu2.js';
import '@ui5/webcomponents-icons/dist/message-error.js';
import '@ui5/webcomponents-icons/dist/message-information.js';
import '@ui5/webcomponents-icons/dist/message-popup.js';
import '@ui5/webcomponents-icons/dist/message-success.js';
import '@ui5/webcomponents-icons/dist/message-warning.js';
import '@ui5/webcomponents-icons/dist/microphone.js';
import '@ui5/webcomponents-icons/dist/mileage.js';
import '@ui5/webcomponents-icons/dist/minimize.js';
import '@ui5/webcomponents-icons/dist/mirrored-task-circle-2.js';
import '@ui5/webcomponents-icons/dist/mirrored-task-circle.js';
import '@ui5/webcomponents-icons/dist/money-bills.js';
import '@ui5/webcomponents-icons/dist/monitor-payments.js';
import '@ui5/webcomponents-icons/dist/move.js';
import '@ui5/webcomponents-icons/dist/mri-scan.js';
import '@ui5/webcomponents-icons/dist/multi-select.js';
import '@ui5/webcomponents-icons/dist/multiple-bar-chart.js';
import '@ui5/webcomponents-icons/dist/multiple-line-chart.js';
import '@ui5/webcomponents-icons/dist/multiple-pie-chart.js';
import '@ui5/webcomponents-icons/dist/multiple-radar-chart.js';
import '@ui5/webcomponents-icons/dist/multiselect-all.js';
import '@ui5/webcomponents-icons/dist/multiselect-none.js';
import '@ui5/webcomponents-icons/dist/my-sales-order.js';
import '@ui5/webcomponents-icons/dist/my-view.js';
import '@ui5/webcomponents-icons/dist/nav-back.js';
import '@ui5/webcomponents-icons/dist/navigation-down-arrow.js';
import '@ui5/webcomponents-icons/dist/navigation-left-arrow.js';
import '@ui5/webcomponents-icons/dist/navigation-right-arrow.js';
import '@ui5/webcomponents-icons/dist/navigation-up-arrow.js';
import '@ui5/webcomponents-icons/dist/negative.js';
import '@ui5/webcomponents-icons/dist/newspaper.js';
import '@ui5/webcomponents-icons/dist/non-binary.js';
import '@ui5/webcomponents-icons/dist/not-editable.js';
import '@ui5/webcomponents-icons/dist/notes.js';
import '@ui5/webcomponents-icons/dist/notification-2.js';
import '@ui5/webcomponents-icons/dist/notification.js';
import '@ui5/webcomponents-icons/dist/number-sign.js';
import '@ui5/webcomponents-icons/dist/numbered-text.js';
import '@ui5/webcomponents-icons/dist/nurse.js';
import '@ui5/webcomponents-icons/dist/nutrition-activity.js';
import '@ui5/webcomponents-icons/dist/official-service.js';
import '@ui5/webcomponents-icons/dist/offsite-work.js';
import '@ui5/webcomponents-icons/dist/open-command-field.js';
import '@ui5/webcomponents-icons/dist/open-folder.js';
import '@ui5/webcomponents-icons/dist/opportunities.js';
import '@ui5/webcomponents-icons/dist/opportunity.js';
import '@ui5/webcomponents-icons/dist/order-status.js';
import '@ui5/webcomponents-icons/dist/org-chart.js';
import '@ui5/webcomponents-icons/dist/outbox.js';
import '@ui5/webcomponents-icons/dist/outdent.js';
import '@ui5/webcomponents-icons/dist/outgoing-call.js';
import '@ui5/webcomponents-icons/dist/overflow.js';
import '@ui5/webcomponents-icons/dist/overlay.js';
import '@ui5/webcomponents-icons/dist/overview-chart.js';
import '@ui5/webcomponents-icons/dist/paging.js';
import '@ui5/webcomponents-icons/dist/paid-leave.js';
import '@ui5/webcomponents-icons/dist/paint-bucket.js';
import '@ui5/webcomponents-icons/dist/palette.js';
import '@ui5/webcomponents-icons/dist/paper-plane.js';
import '@ui5/webcomponents-icons/dist/passenger-train.js';
import '@ui5/webcomponents-icons/dist/past.js';
import '@ui5/webcomponents-icons/dist/paste.js';
import '@ui5/webcomponents-icons/dist/pause.js';
import '@ui5/webcomponents-icons/dist/payment-approval.js';
import '@ui5/webcomponents-icons/dist/pdf-attachment.js';
import '@ui5/webcomponents-icons/dist/pdf-reader.js';
import '@ui5/webcomponents-icons/dist/pending.js';
import '@ui5/webcomponents-icons/dist/people-connected.js';
import '@ui5/webcomponents-icons/dist/per-diem.js';
import '@ui5/webcomponents-icons/dist/performance.js';
import '@ui5/webcomponents-icons/dist/permission.js';
import '@ui5/webcomponents-icons/dist/person-placeholder.js';
import '@ui5/webcomponents-icons/dist/personnel-view.js';
import '@ui5/webcomponents-icons/dist/pharmacy.js';
import '@ui5/webcomponents-icons/dist/phone.js';
import '@ui5/webcomponents-icons/dist/photo-voltaic.js';
import '@ui5/webcomponents-icons/dist/physical-activity.js';
import '@ui5/webcomponents-icons/dist/picture.js';
import '@ui5/webcomponents-icons/dist/pie-chart.js';
import '@ui5/webcomponents-icons/dist/pipeline-analysis.js';
import '@ui5/webcomponents-icons/dist/pixelate.js';
import '@ui5/webcomponents-icons/dist/play.js';
import '@ui5/webcomponents-icons/dist/pool.js';
import '@ui5/webcomponents-icons/dist/popup-window.js';
import '@ui5/webcomponents-icons/dist/positive.js';
import '@ui5/webcomponents-icons/dist/post.js';
import '@ui5/webcomponents-icons/dist/ppt-attachment.js';
import '@ui5/webcomponents-icons/dist/present.js';
import '@ui5/webcomponents-icons/dist/primary-key.js';
import '@ui5/webcomponents-icons/dist/print.js';
import '@ui5/webcomponents-icons/dist/private.js';
import '@ui5/webcomponents-icons/dist/process.js';
import '@ui5/webcomponents-icons/dist/product.js';
import '@ui5/webcomponents-icons/dist/program-triangles-2.js';
import '@ui5/webcomponents-icons/dist/program-triangles.js';
import '@ui5/webcomponents-icons/dist/project-definition-triangle-2.js';
import '@ui5/webcomponents-icons/dist/project-definition-triangle.js';
import '@ui5/webcomponents-icons/dist/projector.js';
import '@ui5/webcomponents-icons/dist/provision.js';
import '@ui5/webcomponents-icons/dist/pull-down.js';
import '@ui5/webcomponents-icons/dist/pushpin-off.js';
import '@ui5/webcomponents-icons/dist/pushpin-on.js';
import '@ui5/webcomponents-icons/dist/puzzle.js';
import '@ui5/webcomponents-icons/dist/qr-code.js';
import '@ui5/webcomponents-icons/dist/quality-issue.js';
import '@ui5/webcomponents-icons/dist/question-mark.js';
import '@ui5/webcomponents-icons/dist/radar-chart.js';
import '@ui5/webcomponents-icons/dist/receipt.js';
import '@ui5/webcomponents-icons/dist/record.js';
import '@ui5/webcomponents-icons/dist/redo.js';
import '@ui5/webcomponents-icons/dist/refresh.js';
import '@ui5/webcomponents-icons/dist/repost.js';
import '@ui5/webcomponents-icons/dist/request.js';
import '@ui5/webcomponents-icons/dist/reset.js';
import '@ui5/webcomponents-icons/dist/resize-corner.js';
import '@ui5/webcomponents-icons/dist/resize-horizontal.js';
import '@ui5/webcomponents-icons/dist/resize-vertical.js';
import '@ui5/webcomponents-icons/dist/resize.js';
import '@ui5/webcomponents-icons/dist/response.js';
import '@ui5/webcomponents-icons/dist/responsive.js';
import '@ui5/webcomponents-icons/dist/restart.js';
import '@ui5/webcomponents-icons/dist/retail-store-manager.js';
import '@ui5/webcomponents-icons/dist/retail-store.js';
import '@ui5/webcomponents-icons/dist/rhombus-milestone-2.js';
import '@ui5/webcomponents-icons/dist/rhombus-milestone.js';
import '@ui5/webcomponents-icons/dist/role.js';
import '@ui5/webcomponents-icons/dist/rotate.js';
import '@ui5/webcomponents-icons/dist/s4hana.js';
import '@ui5/webcomponents-icons/dist/sales-document.js';
import '@ui5/webcomponents-icons/dist/sales-notification.js';
import '@ui5/webcomponents-icons/dist/sales-order-item.js';
import '@ui5/webcomponents-icons/dist/sales-order.js';
import '@ui5/webcomponents-icons/dist/sales-quote.js';
import '@ui5/webcomponents-icons/dist/sap-box.js';
import '@ui5/webcomponents-icons/dist/sap-logo-shape.js';
import '@ui5/webcomponents-icons/dist/sap-ui5.js';
import '@ui5/webcomponents-icons/dist/save.js';
import '@ui5/webcomponents-icons/dist/scatter-chart.js';
import '@ui5/webcomponents-icons/dist/scissors.js';
import '@ui5/webcomponents-icons/dist/screen-split-one.js';
import '@ui5/webcomponents-icons/dist/screen-split-three.js';
import '@ui5/webcomponents-icons/dist/screen-split-two.js';
import '@ui5/webcomponents-icons/dist/search.js';
import '@ui5/webcomponents-icons/dist/select-appointments.js';
import '@ui5/webcomponents-icons/dist/settings.js';
import '@ui5/webcomponents-icons/dist/share-2.js';
import '@ui5/webcomponents-icons/dist/share.js';
import '@ui5/webcomponents-icons/dist/shelf.js';
import '@ui5/webcomponents-icons/dist/shield.js';
import '@ui5/webcomponents-icons/dist/shipping-status.js';
import '@ui5/webcomponents-icons/dist/shortcut.js';
import '@ui5/webcomponents-icons/dist/show-edit.js';
import '@ui5/webcomponents-icons/dist/show.js';
import '@ui5/webcomponents-icons/dist/signature.js';
import '@ui5/webcomponents-icons/dist/simple-payment.js';
import '@ui5/webcomponents-icons/dist/simulate.js';
import '@ui5/webcomponents-icons/dist/slim-arrow-down.js';
import '@ui5/webcomponents-icons/dist/slim-arrow-left.js';
import '@ui5/webcomponents-icons/dist/slim-arrow-right.js';
import '@ui5/webcomponents-icons/dist/slim-arrow-up.js';
import '@ui5/webcomponents-icons/dist/soccer.js';
import '@ui5/webcomponents-icons/dist/sonography.js';
import '@ui5/webcomponents-icons/dist/sort-ascending.js';
import '@ui5/webcomponents-icons/dist/sort-descending.js';
import '@ui5/webcomponents-icons/dist/sort.js';
import '@ui5/webcomponents-icons/dist/sorting-ranking.js';
import '@ui5/webcomponents-icons/dist/sound-loud.js';
import '@ui5/webcomponents-icons/dist/sound-off.js';
import '@ui5/webcomponents-icons/dist/sound.js';
import '@ui5/webcomponents-icons/dist/source-code.js';
import '@ui5/webcomponents-icons/dist/space-navigation.js';
import '@ui5/webcomponents-icons/dist/split.js';
import '@ui5/webcomponents-icons/dist/status-completed.js';
import '@ui5/webcomponents-icons/dist/status-critical.js';
import '@ui5/webcomponents-icons/dist/status-error.js';
import '@ui5/webcomponents-icons/dist/status-in-process.js';
import '@ui5/webcomponents-icons/dist/status-inactive.js';
import '@ui5/webcomponents-icons/dist/status-negative.js';
import '@ui5/webcomponents-icons/dist/status-positive.js';
import '@ui5/webcomponents-icons/dist/step.js';
import '@ui5/webcomponents-icons/dist/stethoscope.js';
import '@ui5/webcomponents-icons/dist/stop.js';
import '@ui5/webcomponents-icons/dist/strikethrough.js';
import '@ui5/webcomponents-icons/dist/study-leave.js';
import '@ui5/webcomponents-icons/dist/subway-train.js';
import '@ui5/webcomponents-icons/dist/suitcase.js';
import '@ui5/webcomponents-icons/dist/sum.js';
import '@ui5/webcomponents-icons/dist/supplier.js';
import '@ui5/webcomponents-icons/dist/survey.js';
import '@ui5/webcomponents-icons/dist/switch-classes.js';
import '@ui5/webcomponents-icons/dist/switch-views.js';
import '@ui5/webcomponents-icons/dist/synchronize.js';
import '@ui5/webcomponents-icons/dist/syntax.js';
import '@ui5/webcomponents-icons/dist/syringe.js';
import '@ui5/webcomponents-icons/dist/sys-add.js';
import '@ui5/webcomponents-icons/dist/sys-back-2.js';
import '@ui5/webcomponents-icons/dist/sys-back.js';
import '@ui5/webcomponents-icons/dist/sys-cancel-2.js';
import '@ui5/webcomponents-icons/dist/sys-cancel.js';
import '@ui5/webcomponents-icons/dist/sys-enter-2.js';
import '@ui5/webcomponents-icons/dist/sys-enter.js';
import '@ui5/webcomponents-icons/dist/sys-find-next.js';
import '@ui5/webcomponents-icons/dist/sys-find.js';
import '@ui5/webcomponents-icons/dist/sys-first-page.js';
import '@ui5/webcomponents-icons/dist/sys-help-2.js';
import '@ui5/webcomponents-icons/dist/sys-help.js';
import '@ui5/webcomponents-icons/dist/sys-last-page.js';
import '@ui5/webcomponents-icons/dist/sys-minus.js';
import '@ui5/webcomponents-icons/dist/sys-monitor.js';
import '@ui5/webcomponents-icons/dist/sys-next-page.js';
import '@ui5/webcomponents-icons/dist/sys-prev-page.js';
import '@ui5/webcomponents-icons/dist/system-exit-2.js';
import '@ui5/webcomponents-icons/dist/system-exit.js';
import '@ui5/webcomponents-icons/dist/table-chart.js';
import '@ui5/webcomponents-icons/dist/table-column.js';
import '@ui5/webcomponents-icons/dist/table-row.js';
import '@ui5/webcomponents-icons/dist/table-view.js';
import '@ui5/webcomponents-icons/dist/tag-cloud-chart.js';
import '@ui5/webcomponents-icons/dist/tag.js';
import '@ui5/webcomponents-icons/dist/tags.js';
import '@ui5/webcomponents-icons/dist/target-group.js';
import '@ui5/webcomponents-icons/dist/task.js';
import '@ui5/webcomponents-icons/dist/taxi.js';
import '@ui5/webcomponents-icons/dist/technical-object.js';
import '@ui5/webcomponents-icons/dist/temperature.js';
import '@ui5/webcomponents-icons/dist/text-align-center.js';
import '@ui5/webcomponents-icons/dist/text-align-justified.js';
import '@ui5/webcomponents-icons/dist/text-align-left.js';
import '@ui5/webcomponents-icons/dist/text-align-right.js';
import '@ui5/webcomponents-icons/dist/text-color.js';
import '@ui5/webcomponents-icons/dist/text-formatting.js';
import '@ui5/webcomponents-icons/dist/text.js';
import '@ui5/webcomponents-icons/dist/theater.js';
import '@ui5/webcomponents-icons/dist/thing-type.js';
import '@ui5/webcomponents-icons/dist/thumb-down.js';
import '@ui5/webcomponents-icons/dist/thumb-up.js';
import '@ui5/webcomponents-icons/dist/time-account.js';
import '@ui5/webcomponents-icons/dist/time-entry-request.js';
import '@ui5/webcomponents-icons/dist/time-off.js';
import '@ui5/webcomponents-icons/dist/time-overtime.js';
import '@ui5/webcomponents-icons/dist/timesheet.js';
import '@ui5/webcomponents-icons/dist/to-be-reviewed.js';
import '@ui5/webcomponents-icons/dist/toaster-down.js';
import '@ui5/webcomponents-icons/dist/toaster-top.js';
import '@ui5/webcomponents-icons/dist/toaster-up.js';
import '@ui5/webcomponents-icons/dist/tools-opportunity.js';
import '@ui5/webcomponents-icons/dist/touch.js';
import '@ui5/webcomponents-icons/dist/translate.js';
import '@ui5/webcomponents-icons/dist/travel-expense-report.js';
import '@ui5/webcomponents-icons/dist/travel-expense.js';
import '@ui5/webcomponents-icons/dist/travel-itinerary.js';
import '@ui5/webcomponents-icons/dist/travel-request.js';
import '@ui5/webcomponents-icons/dist/tree.js';
import '@ui5/webcomponents-icons/dist/trend-down.js';
import '@ui5/webcomponents-icons/dist/trend-up.js';
import '@ui5/webcomponents-icons/dist/tri-state.js';
import '@ui5/webcomponents-icons/dist/trip-report.js';
import '@ui5/webcomponents-icons/dist/two-keys.js';
import '@ui5/webcomponents-icons/dist/ui-notifications.js';
import '@ui5/webcomponents-icons/dist/umbrella.js';
import '@ui5/webcomponents-icons/dist/underline-text.js';
import '@ui5/webcomponents-icons/dist/undo.js';
import '@ui5/webcomponents-icons/dist/unfavorite.js';
import '@ui5/webcomponents-icons/dist/unlocked.js';
import '@ui5/webcomponents-icons/dist/unpaid-leave.js';
import '@ui5/webcomponents-icons/dist/unsynchronize.js';
import '@ui5/webcomponents-icons/dist/unwired.js';
import '@ui5/webcomponents-icons/dist/up.js';
import '@ui5/webcomponents-icons/dist/upload-to-cloud.js';
import '@ui5/webcomponents-icons/dist/upload.js';
import '@ui5/webcomponents-icons/dist/upstacked-chart.js';
import '@ui5/webcomponents-icons/dist/user-edit.js';
import '@ui5/webcomponents-icons/dist/user-settings.js';
import '@ui5/webcomponents-icons/dist/validate.js';
import '@ui5/webcomponents-icons/dist/value-help.js';
import '@ui5/webcomponents-icons/dist/vds-file.js';
import '@ui5/webcomponents-icons/dist/vehicle-repair.js';
import '@ui5/webcomponents-icons/dist/vertical-bar-chart-2.js';
import '@ui5/webcomponents-icons/dist/vertical-bar-chart.js';
import '@ui5/webcomponents-icons/dist/vertical-bullet-chart.js';
import '@ui5/webcomponents-icons/dist/vertical-grip.js';
import '@ui5/webcomponents-icons/dist/vertical-stacked-chart.js';
import '@ui5/webcomponents-icons/dist/vertical-waterfall-chart.js';
import '@ui5/webcomponents-icons/dist/video.js';
import '@ui5/webcomponents-icons/dist/visits.js';
import '@ui5/webcomponents-icons/dist/waiver.js';
import '@ui5/webcomponents-icons/dist/wallet.js';
import '@ui5/webcomponents-icons/dist/warning.js';
import '@ui5/webcomponents-icons/dist/warning2.js';
import '@ui5/webcomponents-icons/dist/washing-machine.js';
import '@ui5/webcomponents-icons/dist/weather-proofing.js';
import '@ui5/webcomponents-icons/dist/web-cam.js';
import '@ui5/webcomponents-icons/dist/widgets.js';
import '@ui5/webcomponents-icons/dist/windows-doors.js';
import '@ui5/webcomponents-icons/dist/work-history.js';
import '@ui5/webcomponents-icons/dist/workflow-tasks.js';
import '@ui5/webcomponents-icons/dist/world.js';
import '@ui5/webcomponents-icons/dist/wounds-doc.js';
import '@ui5/webcomponents-icons/dist/wrench.js';
import '@ui5/webcomponents-icons/dist/write-new-document.js';
import '@ui5/webcomponents-icons/dist/write-new.js';
import '@ui5/webcomponents-icons/dist/x-ray.js';
import '@ui5/webcomponents-icons/dist/zoom-in.js';
import '@ui5/webcomponents-icons/dist/zoom-out.js';
