import accordion from './components/accordion';
import button from './components/button';
import input from './components/input';
import card from './components/card';
import label from './components/label';
import textarea from './components/textarea';
import checkbox from './components/checkbox';
import datepicker from './components/datepicker';
import popover from './components/popover';
import avatar from './components/avatar';
import badge from './components/badge';
import select from './components/select';
import alert from './components/alert';
import radio from './components/radio';
import range from './components/range';
import _switch from './components/switch';
import sidebar from './components/sidebar';
import separator from './components/separator';
import skeleton from './components/skeleton';
import collapsible from './components/collapsible';
import tile from './components/tile';
import tag from './components/tag';
import icon from './components/icon';
import infoPage from './components/info-page';
import spinner from './components/spinner';
import fieldset from './components/fieldset';
import tooltip from './components/tooltip';
import progress from './components/progress';
import pagination from './components/pagination';
import tabs from './components/tabs';
import text from './components/text';
import dialog from './components/dialog';
import table from './components/table';
import menu from './components/menu';
import toolbar from './components/toolbar';

import { setColorScheme } from './utils/theme';

window.Harmonia = { setColorScheme };

document.addEventListener('alpine:init', () => {
  window.Alpine.plugin(accordion);
  window.Alpine.plugin(button);
  window.Alpine.plugin(input);
  window.Alpine.plugin(card);
  window.Alpine.plugin(datepicker);
  window.Alpine.plugin(label);
  window.Alpine.plugin(textarea);
  window.Alpine.plugin(checkbox);
  window.Alpine.plugin(popover);
  window.Alpine.plugin(avatar);
  window.Alpine.plugin(badge);
  window.Alpine.plugin(select);
  window.Alpine.plugin(alert);
  window.Alpine.plugin(radio);
  window.Alpine.plugin(range);
  window.Alpine.plugin(_switch);
  window.Alpine.plugin(sidebar);
  window.Alpine.plugin(separator);
  window.Alpine.plugin(skeleton);
  window.Alpine.plugin(collapsible);
  window.Alpine.plugin(tile);
  window.Alpine.plugin(tag);
  window.Alpine.plugin(icon);
  window.Alpine.plugin(infoPage);
  window.Alpine.plugin(spinner);
  window.Alpine.plugin(fieldset);
  window.Alpine.plugin(tooltip);
  window.Alpine.plugin(progress);
  window.Alpine.plugin(pagination);
  window.Alpine.plugin(tabs);
  window.Alpine.plugin(text);
  window.Alpine.plugin(dialog);
  window.Alpine.plugin(table);
  window.Alpine.plugin(menu);
  window.Alpine.plugin(toolbar);
});
