import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import {
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
    AlertDialogTrigger,
} from '@/components/ui/alert-dialog'
import { AspectRatio } from '@/components/ui/aspect-ratio'
import {
    AutoForm,
    AutoFormField,
    AutoFormFieldArray,
    AutoFormFieldBoolean,
    AutoFormFieldDate,
    AutoFormFieldEnum,
    AutoFormFieldFile,
    AutoFormFieldInput,
    AutoFormFieldNumber,
    AutoFormFieldObject,
    AutoFormLabel,
} from '@/components/ui/auto-form'
import { DependencyType } from './components/ui/auto-form/interface'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Badge } from '@/components/ui/badge'
import {
    Breadcrumb,
    BreadcrumbEllipsis,
    BreadcrumbItem,
    BreadcrumbLink,
    BreadcrumbList,
    BreadcrumbPage,
    BreadcrumbSeparator,
} from '@/components/ui/breadcrumb'
import { Button } from '@/components/ui/button'
import {
    Calendar,
    CalendarCell,
    CalendarCellTrigger,
    CalendarGrid,
    CalendarGridBody,
    CalendarGridHead,
    CalendarGridRow,
    CalendarHeadCell,
    CalendarHeader,
    CalendarHeading,
    CalendarNextButton,
    CalendarPrevButton,
    CalendarSelect,
} from '@/components/ui/calendar'
import { createDecade, createYear, toDate } from 'radix-vue/date'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from '@/components/ui/carousel'
import { Checkbox } from '@/components/ui/checkbox'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { Combobox } from '@/components/ui/combobox'
import {
    Command,
    CommandEmpty,
    CommandGroup,
    CommandInput,
    CommandItem,
    CommandList,
    CommandSeparator,
    CommandShortcut,
    CommandDialog,
} from '@/components/ui/command'
import {
    ContextMenu,
    ContextMenuCheckboxItem,
    ContextMenuContent,
    ContextMenuGroup,
    ContextMenuItem,
    ContextMenuLabel,
    ContextMenuRadioGroup,
    ContextMenuRadioItem,
    ContextMenuSeparator,
    ContextMenuShortcut,
    ContextMenuSub,
    ContextMenuSubContent,
    ContextMenuSubTrigger,
    ContextMenuTrigger,
} from '@/components/ui/context-menu'
import { DataTable, DataTableColumnHeader, DataTablePagination } from '@/components/ui/data-table'
import { DatePicker } from '@/components/ui/date-picker'
import {
    Dialog,
    DialogClose,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogScrollContent,
    DialogTitle,
    DialogTrigger,
} from '@/components/ui/dialog'
import {
    Drawer,
    DrawerClose,
    DrawerContent,
    DrawerDescription,
    DrawerFooter,
    DrawerHeader,
    DrawerTitle,
    DrawerOverlay,
    DrawerPortal,
    DrawerTrigger,
} from '@/components/ui/drawer'
import {
    DropdownMenu,
    DropdownMenuCheckboxItem,
    DropdownMenuContent,
    DropdownMenuGroup,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuRadioGroup,
    DropdownMenuRadioItem,
    DropdownMenuSeparator,
    DropdownMenuShortcut,
    DropdownMenuSub,
    DropdownMenuSubContent,
    DropdownMenuSubTrigger,
    DropdownMenuTrigger,
    DropdownMenuPortal,
} from '@/components/ui/dropdown-menu'
import { Form, FormField, FormItem, FormLabel, FormControl, FormDescription, FormMessage } from '@/components/ui/form'
import { HoverCard, HoverCardContent, HoverCardTrigger } from '@/components/ui/hover-card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
    Menubar,
    MenubarContent,
    MenubarItem,
    MenubarMenu,
    MenubarSeparator,
    MenubarShortcut,
    MenubarTrigger,
    MenubarCheckboxItem,
    MenubarGroup,
    MenubarLabel,
    MenubarRadioGroup,
    MenubarRadioItem,
    MenubarSub,
    MenubarSubContent,
    MenubarSubTrigger,
} from '@/components/ui/menubar'
import {
    NavigationMenu,
    NavigationMenuContent,
    NavigationMenuItem,
    NavigationMenuLink,
    NavigationMenuList,
    NavigationMenuTrigger,
    NavigationMenuViewport,
    NavigationMenuIndicator,
} from '@/components/ui/navigation-menu'
import {
    NumberField,
    NumberFieldContent,
    NumberFieldDecrement,
    NumberFieldIncrement,
    NumberFieldInput,
} from '@/components/ui/number-field'
import {
    Pagination,
    PaginationEllipsis,
    PaginationFirst,
    PaginationLast,
    PaginationList,
    PaginationListItem,
    PaginationNext,
    PaginationPrev,
} from '@/components/ui/pagination'
import { PinInput, PinInputGroup, PinInputInput, PinInputSeparator } from '@/components/ui/pin-input'
import { Popover, PopoverTrigger, PopoverContent } from '@/components/ui/popover'
import { Progress } from '@/components/ui/progress'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import {
    RangeCalendar,
    RangeCalendarCell,
    RangeCalendarCellTrigger,
    RangeCalendarGrid,
    RangeCalendarGridBody,
    RangeCalendarGridHead,
    RangeCalendarGridRow,
    RangeCalendarHeadCell,
    RangeCalendarHeader,
    RangeCalendarHeading,
    RangeCalendarNextButton,
    RangeCalendarPrevButton,
} from '@/components/ui/range-calendar'
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from '@/components/ui/resizable'
import { ScrollArea, ScrollBar } from '@/components/ui/scroll-area'
import {
    Select,
    SelectContent,
    SelectGroup,
    SelectItem,
    SelectItemText,
    SelectLabel,
    SelectScrollDownButton,
    SelectScrollUpButton,
    SelectSeparator,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select'
import { Separator } from '@/components/ui/separator'
import {
    Sheet,
    SheetClose,
    SheetContent,
    SheetDescription,
    SheetFooter,
    SheetHeader,
    SheetTitle,
    SheetTrigger,
} from '@/components/ui/sheet'
import {
    Sidebar,
    SidebarContent,
    SidebarFooter,
    SidebarGroup,
    SidebarGroupAction,
    SidebarGroupContent,
    SidebarGroupLabel,
    SidebarHeader,
    SidebarInput,
    SidebarInset,
    SidebarMenu,
    SidebarMenuAction,
    SidebarMenuBadge,
    SidebarMenuButton,
    SidebarMenuItem,
    SidebarMenuSkeleton,
    SidebarMenuSub,
    SidebarMenuSubButton,
    SidebarMenuSubItem,
    SidebarProvider,
    SidebarRail,
    SidebarSeparator,
    SidebarTrigger,
    useSidebar,
} from '@/components/ui/sidebar'
import { Skeleton } from '@/components/ui/skeleton'
import { Slider } from '@/components/ui/slider'
import {
    Stepper,
    StepperDescription,
    StepperIndicator,
    StepperItem,
    StepperSeparator,
    StepperTitle,
    StepperTrigger,
} from '@/components/ui/stepper'
import { Switch } from '@/components/ui/switch'
import {
    Table,
    TableBody,
    TableCaption,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
    TableEmpty,
    TableFooter,
} from '@/components/ui/table'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
    TagsInput,
    TagsInputInput,
    TagsInputItem,
    TagsInputItemDelete,
    TagsInputItemText,
} from '@/components/ui/tags-input'
import { Textarea } from '@/components/ui/textarea'
import {
    Toast,
    ToastAction,
    ToastClose,
    ToastDescription,
    Toaster,
    ToastProvider,
    ToastTitle,
    ToastViewport,
    toast,
    useToast,
} from '@/components/ui/toast'
import { Toggle } from '@/components/ui/toggle'
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'

import { Tree } from '@/components/ui/tree'
import { Calendar as VCalendar } from '@/components/ui/v-calendar'

import './assets/index.css'
import './assets/global.css'

import { useColorMode } from '@vueuse/core'

import { valueUpdater } from './lib/utils'

const components = {
    HAccordion: Accordion,
    HAccordionItem: AccordionItem,
    HAccordionTrigger: AccordionTrigger,
    HAccordionContent: AccordionContent,
    HAlert: Alert,
    HAlertDescription: AlertDescription,
    HAlertTitle: AlertTitle,
    HAlertDialog: AlertDialog,
    HAlertDialogAction: AlertDialogAction,
    HAlertDialogCancel: AlertDialogCancel,
    HAlertDialogContent: AlertDialogContent,
    HAlertDialogDescription: AlertDialogDescription,
    HAlertDialogFooter: AlertDialogFooter,
    HAlertDialogHeader: AlertDialogHeader,
    HAlertDialogTitle: AlertDialogTitle,
    HAlertDialogTrigger: AlertDialogTrigger,
    HAspectRatio: AspectRatio,
    HAutoForm: AutoForm,
    HAutoFormField: AutoFormField,
    HAutoFormFieldArray: AutoFormFieldArray,
    HAutoFormFieldBoolean: AutoFormFieldBoolean,
    HAutoFormFieldDate: AutoFormFieldDate,
    HAutoFormFieldEnum: AutoFormFieldEnum,
    HAutoFormFieldFile: AutoFormFieldFile,
    HAutoFormFieldInput: AutoFormFieldInput,
    HAutoFormFieldNumber: AutoFormFieldNumber,
    HAutoFormFieldObject: AutoFormFieldObject,
    HAutoFormLabel: AutoFormLabel,
    HAvatar: Avatar,
    HAvatarFallback: AvatarFallback,
    HAvatarImage: AvatarImage,
    HBadge: Badge,
    HBreadcrumb: Breadcrumb,
    HBreadcrumbEllipsis: BreadcrumbEllipsis,
    HBreadcrumbItem: BreadcrumbItem,
    HBreadcrumbLink: BreadcrumbLink,
    HBreadcrumbList: BreadcrumbList,
    HBreadcrumbPage: BreadcrumbPage,
    HBreadcrumbSeparator: BreadcrumbSeparator,
    HButton: Button,
    HCalendar: Calendar,
    HCalendarCell: CalendarCell,
    HCalendarCellTrigger: CalendarCellTrigger,
    HCalendarGrid: CalendarGrid,
    HCalendarGridBody: CalendarGridBody,
    HCalendarGridHead: CalendarGridHead,
    HCalendarGridRow: CalendarGridRow,
    HCalendarHeadCell: CalendarHeadCell,
    HCalendarHeader: CalendarHeader,
    HCalendarHeading: CalendarHeading,
    HCalendarNextButton: CalendarNextButton,
    HCalendarPrevButton: CalendarPrevButton,
    HCalendarSelect: CalendarSelect,
    HCard: Card,
    HCardContent: CardContent,
    HCardDescription: CardDescription,
    HCardFooter: CardFooter,
    HCardHeader: CardHeader,
    HCardTitle: CardTitle,
    HCarousel: Carousel,
    HCarouselContent: CarouselContent,
    HCarouselItem: CarouselItem,
    HCarouselNext: CarouselNext,
    HCarouselPrevious: CarouselPrevious,
    HCheckbox: Checkbox,
    HCollapsible: Collapsible,
    HCollapsibleContent: CollapsibleContent,
    HCollapsibleTrigger: CollapsibleTrigger,
    HCombobox: Combobox,
    HCommand: Command,
    HCommandEmpty: CommandEmpty,
    HCommandGroup: CommandGroup,
    HCommandInput: CommandInput,
    HCommandItem: CommandItem,
    HCommandList: CommandList,
    HCommandSeparator: CommandSeparator,
    HCommandShortcut: CommandShortcut,
    HCommandDialog: CommandDialog,
    HContextMenu: ContextMenu,
    HContextMenuCheckboxItem: ContextMenuCheckboxItem,
    HContextMenuContent: ContextMenuContent,
    HContextMenuGroup: ContextMenuGroup,
    HContextMenuItem: ContextMenuItem,
    HContextMenuLabel: ContextMenuLabel,
    HContextMenuRadioGroup: ContextMenuRadioGroup,
    HContextMenuRadioItem: ContextMenuRadioItem,
    HContextMenuSeparator: ContextMenuSeparator,
    HContextMenuShortcut: ContextMenuShortcut,
    HContextMenuSub: ContextMenuSub,
    HContextMenuSubContent: ContextMenuSubContent,
    HContextMenuSubTrigger: ContextMenuSubTrigger,
    HContextMenuTrigger: ContextMenuTrigger,
    HDataTable: DataTable,
    HDataTableColumnHeader: DataTableColumnHeader,
    HDataTablePagination: DataTablePagination,
    HDatePicker: DatePicker,
    HDialog: Dialog,
    HDialogClose: DialogClose,
    HDialogContent: DialogContent,
    HDialogDescription: DialogDescription,
    HDialogFooter: DialogFooter,
    HDialogHeader: DialogHeader,
    HDialogScrollContent: DialogScrollContent,
    HDialogTitle: DialogTitle,
    HDialogTrigger: DialogTrigger,
    HDrawer: Drawer,
    HDrawerClose: DrawerClose,
    HDrawerContent: DrawerContent,
    HDrawerDescription: DrawerDescription,
    HDrawerFooter: DrawerFooter,
    HDrawerHeader: DrawerHeader,
    HDrawerTitle: DrawerTitle,
    HDrawerOverlay: DrawerOverlay,
    HDrawerPortal: DrawerPortal,
    HDrawerTrigger: DrawerTrigger,
    HDropdownMenu: DropdownMenu,
    HDropdownMenuCheckboxItem: DropdownMenuCheckboxItem,
    HDropdownMenuContent: DropdownMenuContent,
    HDropdownMenuGroup: DropdownMenuGroup,
    HDropdownMenuItem: DropdownMenuItem,
    HDropdownMenuLabel: DropdownMenuLabel,
    HDropdownMenuRadioGroup: DropdownMenuRadioGroup,
    HDropdownMenuRadioItem: DropdownMenuRadioItem,
    HDropdownMenuSeparator: DropdownMenuSeparator,
    HDropdownMenuShortcut: DropdownMenuShortcut,
    HDropdownMenuSub: DropdownMenuSub,
    HDropdownMenuSubContent: DropdownMenuSubContent,
    HDropdownMenuSubTrigger: DropdownMenuSubTrigger,
    HDropdownMenuTrigger: DropdownMenuTrigger,
    HDropdownMenuPortal: DropdownMenuPortal,
    HForm: Form,
    HFormField: FormField,
    HFormItem: FormItem,
    HFormLabel: FormLabel,
    HFormControl: FormControl,
    HFormDescription: FormDescription,
    HFormMessage: FormMessage,
    HHoverCard: HoverCard,
    HHoverCardContent: HoverCardContent,
    HHoverCardTrigger: HoverCardTrigger,
    HInput: Input,
    HLabel: Label,
    HMenubar: Menubar,
    HMenubarContent: MenubarContent,
    HMenubarItem: MenubarItem,
    HMenubarMenu: MenubarMenu,
    HMenubarSeparator: MenubarSeparator,
    HMenubarShortcut: MenubarShortcut,
    HMenubarTrigger: MenubarTrigger,
    HMenubarCheckboxItem: MenubarCheckboxItem,
    HMenubarGroup: MenubarGroup,
    HMenubarLabel: MenubarLabel,
    HMenubarRadioGroup: MenubarRadioGroup,
    HMenubarRadioItem: MenubarRadioItem,
    HMenubarSub: MenubarSub,
    HMenubarSubContent: MenubarSubContent,
    HMenubarSubTrigger: MenubarSubTrigger,
    HNavigationMenu: NavigationMenu,
    HNavigationMenuContent: NavigationMenuContent,
    HNavigationMenuItem: NavigationMenuItem,
    HNavigationMenuLink: NavigationMenuLink,
    HNavigationMenuList: NavigationMenuList,
    HNavigationMenuTrigger: NavigationMenuTrigger,
    HNavigationMenuViewport: NavigationMenuViewport,
    HNavigationMenuIndicator: NavigationMenuIndicator,
    HNumberField: NumberField,
    HNumberFieldContent: NumberFieldContent,
    HNumberFieldDecrement: NumberFieldDecrement,
    HNumberFieldIncrement: NumberFieldIncrement,
    HNumberFieldInput: NumberFieldInput,
    HPagination: Pagination,
    HPaginationEllipsis: PaginationEllipsis,
    HPaginationFirst: PaginationFirst,
    HPaginationLast: PaginationLast,
    HPaginationList: PaginationList,
    HPaginationListItem: PaginationListItem,
    HPaginationNext: PaginationNext,
    HPaginationPrev: PaginationPrev,
    HPinInput: PinInput,
    HPinInputGroup: PinInputGroup,
    HPinInputInput: PinInputInput,
    HPinInputSeparator: PinInputSeparator,
    HPopover: Popover,
    HPopoverTrigger: PopoverTrigger,
    HPopoverContent: PopoverContent,
    HProgress: Progress,
    HRadioGroup: RadioGroup,
    HRadioGroupItem: RadioGroupItem,
    HRangeCalendar: RangeCalendar,
    HRangeCalendarCell: RangeCalendarCell,
    HRangeCalendarCellTrigger: RangeCalendarCellTrigger,
    HRangeCalendarGrid: RangeCalendarGrid,
    HRangeCalendarGridBody: RangeCalendarGridBody,
    HRangeCalendarGridHead: RangeCalendarGridHead,
    HRangeCalendarGridRow: RangeCalendarGridRow,
    HRangeCalendarHeadCell: RangeCalendarHeadCell,
    HRangeCalendarHeader: RangeCalendarHeader,
    HRangeCalendarHeading: RangeCalendarHeading,
    HRangeCalendarNextButton: RangeCalendarNextButton,
    HRangeCalendarPrevButton: RangeCalendarPrevButton,
    HResizableHandle: ResizableHandle,
    HResizablePanel: ResizablePanel,
    HResizablePanelGroup: ResizablePanelGroup,
    HScrollArea: ScrollArea,
    HScrollBar: ScrollBar,
    HSelect: Select,
    HSelectContent: SelectContent,
    HSelectGroup: SelectGroup,
    HSelectItem: SelectItem,
    HSelectItemText: SelectItemText,
    HSelectLabel: SelectLabel,
    HSelectScrollDownButton: SelectScrollDownButton,
    HSelectScrollUpButton: SelectScrollUpButton,
    HSelectSeparator: SelectSeparator,
    HSelectTrigger: SelectTrigger,
    HSelectValue: SelectValue,
    HSeparator: Separator,
    HSheet: Sheet,
    HSheetClose: SheetClose,
    HSheetContent: SheetContent,
    HSheetDescription: SheetDescription,
    HSheetFooter: SheetFooter,
    HSheetHeader: SheetHeader,
    HSheetTitle: SheetTitle,
    HSheetTrigger: SheetTrigger,
    HSidebar: Sidebar,
    HSidebarContent: SidebarContent,
    HSidebarFooter: SidebarFooter,
    HSidebarGroup: SidebarGroup,
    HSidebarGroupAction: SidebarGroupAction,
    HSidebarGroupContent: SidebarGroupContent,
    HSidebarGroupLabel: SidebarGroupLabel,
    HSidebarHeader: SidebarHeader,
    HSidebarInput: SidebarInput,
    HSidebarInset: SidebarInset,
    HSidebarMenu: SidebarMenu,
    HSidebarMenuAction: SidebarMenuAction,
    HSidebarMenuBadge: SidebarMenuBadge,
    HSidebarMenuButton: SidebarMenuButton,
    HSidebarMenuItem: SidebarMenuItem,
    HSidebarMenuSkeleton: SidebarMenuSkeleton,
    HSidebarMenuSub: SidebarMenuSub,
    HSidebarMenuSubButton: SidebarMenuSubButton,
    HSidebarMenuSubItem: SidebarMenuSubItem,
    HSidebarProvider: SidebarProvider,
    HSidebarRail: SidebarRail,
    HSidebarSeparator: SidebarSeparator,
    HSidebarTrigger: SidebarTrigger,
    HSkeleton: Skeleton,
    HSlider: Slider,
    HStepper: Stepper,
    HStepperDescription: StepperDescription,
    HStepperIndicator: StepperIndicator,
    HStepperItem: StepperItem,
    HStepperSeparator: StepperSeparator,
    HStepperTitle: StepperTitle,
    HStepperTrigger: StepperTrigger,
    HSwitch: Switch,
    HTable: Table,
    HTableBody: TableBody,
    HTableCaption: TableCaption,
    HTableCell: TableCell,
    HTableHead: TableHead,
    HTableHeader: TableHeader,
    HTableRow: TableRow,
    HTableEmpty: TableEmpty,
    HTableFooter: TableFooter,
    HTabs: Tabs,
    HTabsContent: TabsContent,
    HTabsList: TabsList,
    HTabsTrigger: TabsTrigger,
    HTagsInput: TagsInput,
    HTagsInputInput: TagsInputInput,
    HTagsInputItem: TagsInputItem,
    HTagsInputItemDelete: TagsInputItemDelete,
    HTagsInputItemText: TagsInputItemText,
    HTextarea: Textarea,
    HToast: Toast,
    HToastAction: ToastAction,
    HToastClose: ToastClose,
    HToastDescription: ToastDescription,
    HToaster: Toaster,
    HToastProvider: ToastProvider,
    HToastTitle: ToastTitle,
    HToastViewport: ToastViewport,
    HToggle: Toggle,
    HToggleGroup: ToggleGroup,
    HToggleGroupItem: ToggleGroupItem,
    HTooltip: Tooltip,
    HTooltipContent: TooltipContent,
    HTooltipProvider: TooltipProvider,
    HTooltipTrigger: TooltipTrigger,
    HTree: Tree,
    HVCalendar: VCalendar,
}

const Harmonia = {
    install(app) {
        Object.entries(components).forEach(([name, component]) => {
            app.component(name, component)
        })
    },
    autoForm: {
        DependencyType: DependencyType,
    },
    useSidebar: useSidebar,
    toast: toast,
    useToast: useToast,
    createDecade: createDecade,
    createYear: createYear,
    toDate: toDate,
    themeMode: useColorMode(),
    valueUpdater: valueUpdater,
}

export default Harmonia
